name: bootstrap

on: [push, pull_request]

jobs: 
  bootstrap: 
    runs-on: ubuntu-latest 
    name: bootstrap 
    permissions:
      pages: write
      id-token: write
    steps: 
      - name: Check out source repository 
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 
      - name: Set up Python environment 
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0 
        with: 
          python-version: "3.9" 
      - name: Install sumologic/pandas 
        run: pip install sumologic-sdk==0.1.13 pandas tabulate
      - name: Run python file on path 
        run: python3 ./script/test.py
      - name: create markdown file 
        run: | 
          cat fer.md > $GITHUB_WORKSPACE/script/FER.md 
          rm fer.md 
          ls -R $GITHUB_WORKSPACE
          git add $GITHUB_WORKSPACE/script/FER.md
          git commit -m 'refreshed md'
      #- uses: stefanzweifel/git-auto-commit-action@v5
  # docume:
  #  needs: [bootstrap]
  #  runs-on: ubuntu-latest
  #  environment:                                                                                                                      
  #    name: github-pages 
  #    url: ${{ steps.deployment.outputs.page_url }} 
  #  steps: 
  #    - name: Download pages artifact 
  #      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2 
  #      with: 
  #        name: pages 
  #        path: pages/public
       
  #    #deploy to github pages 
  #    - name: Setup Github Pages 
  #      uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6 
  #    - name: Upload documentation artifact 
  #      uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0 
  #      with: 
  #        path: pages/public 
  #    - name: Deploy to GitHub Pages 
  #      id: deployment 
  #      uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2.0.4
