name: deploy pages

on: [pull_request]
  # workflow_dispatch:
  # workflow_run:
  #   workflows: [bootstrap]
  #   types: [completed]
  #   branches: [deveid-patch-1]

jobs:  
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Set up Ruby and dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y ruby-full build-essential zlib1g-dev
            ls -R
            cat ./gems >> $GITHUB_ENV
            export GEM_HOME="$HOME/gems >> $GITHUB_ENV
            export PATH="$HOME/gems/bin:$PATH" >> $GITHUB_ENV
            source $GITHUB_ENV
  
        - name: Install Jekyll
          run: |
            gem install jekyll bundler
  
        - name: Build Jekyll site
          run: |
            bundle install
            bundle exec jekyll build
        # - name: Build with Jekyll
        #   uses: actions/jekyll-build-pages@v1
        #   with:
        #     source: ./
        #     destination: ./_site
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
  
    # Deployment job
  deploy:
      permissions:
          pages: write
          id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
